import {createRequire} from 'module';import fs from 'fs';const require=createRequire('/opt/browser/package.json');const {chromium}=require('playwright');const browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const ctx=await browser.newContext({viewport:{width:390,height:844}});const p=await ctx.newPage();const base='http://127.0.0.1:3311/';const out=[];
async function test(name,fn){try{await fn();out.push({name,success:true})}catch(e){out.push({name,success:false,error:e.message})}console.log(name,out.at(-1).success)}
async function go(path){await p.goto(base+path,{waitUntil:'networkidle'})}
function assert(x,m){if(!x)throw new Error(m)}
await test('Quantity, pricing tier and landed cost',async()=>{await go('mobil-dikey/390/urun.html?embed=1');await p.getByLabel('Miktar',{exact:true}).fill('5000');assert((await p.locator('[data-output=subtotal]').innerText()).includes('590.000'),'tier total');await p.getByRole('button',{name:'Maliyeti hesapla',exact:true}).click();assert((await p.locator('[data-output=landed-result]').innerText()).includes('Kapınıza toplam'),'landed output')});
await test('Add to cart persists local quantity',async()=>{await p.locator('[data-action=cart]').first().click();assert(await p.evaluate(()=>JSON.parse(sessionStorage.getItem('arasta.cart')).quantity===5000),'cart persistence')});
await test('Comparison tray and selection',async()=>{await go('mobil-dikey/390/arama.html?embed=1');await p.locator('[data-action=compare]').first().click();assert(await p.locator('#compare-tray').isVisible(),'tray');assert(await p.locator('[data-action=compare]').first().getAttribute('aria-pressed')==='true','selected')});
await test('Phone filter sheet works',async()=>{await p.getByRole('button',{name:'Filtrele',exact:true}).click();await p.locator('select[name=city]').selectOption('Denizli');await p.getByRole('button',{name:'Sonuçları göster',exact:true}).click();assert(await p.locator('[data-product]:visible').count()===1,'one Denizli product')});
await test('Command palette navigation',async()=>{await p.keyboard.press('Control+k');await p.locator('#command-search').fill('Güvence');assert(await p.locator('#command-links a').count()===1,'filtered command');await p.locator('#command-links a').click();assert(p.url().includes('/guvence.html'),'navigation')});
await test('FAQ keyboard disclosure',async()=>{await p.locator('summary').first().click();assert(await p.locator('details').first().getAttribute('open')!==null,'FAQ open')});
await test('Theme toggle',async()=>{await p.evaluate(()=>document.querySelector('[data-action=theme]').click());assert(await p.locator('body').getAttribute('data-theme')==='dark','dark')});
await test('VKN validation and saved company fill',async()=>{await go('mobil-dikey/390/kayit.html?embed=1');await p.getByLabel('Vergi kimlik numarası (VKN)',{exact:true}).fill('1234567890');await p.getByRole('button',{name:'Bilgileri getir',exact:true}).click();assert(await p.getByLabel('İşletme adı',{exact:true}).inputValue()==='Dengora Ticaret A.Ş.','autofill')});
await test('RFQ mock draft',async()=>{await go('mobil-dikey/390/teklif-iste.html?embed=1');await p.getByRole('button',{name:'Taslağı AI ile doldur',exact:true}).click();assert(await p.getByLabel('Miktar',{exact:true}).inputValue()==='5000','draft quantity')});
await test('Message submit and translation',async()=>{await go('mobil-dikey/390/mesajlar.html?embed=1');await p.getByLabel('Mesajınız',{exact:true}).fill('Numune renklerini paylaşır mısınız?');await p.getByRole('button',{name:'Mesajı gönder',exact:true}).click();assert((await p.getByRole('log').innerText()).includes('Numune renklerini'),'message');await p.getByRole('button',{name:'TR ⇄ EN çeviri',exact:true}).click();assert((await p.getByRole('log').innerText()).includes('Hello'),'translation')});
await test('Accessible password reveal',async()=>{await go('mobil-dikey/390/giris.html?embed=1');await p.getByLabel('Parola',{exact:true}).fill('example');await p.getByRole('button',{name:'Parolayı göster'}).click();assert(await p.getByLabel('Parola',{exact:true}).getAttribute('type')==='text','reveal')});
await test('Viewer device selection, live iframe, hash and history',async()=>{await p.setViewportSize({width:1440,height:960});await go('index.html');await p.locator('[data-device="laptop/1440"]').click();await p.locator('[data-page="urun"]').click();await p.waitForURL('**#laptop/1440/urun');await p.locator('#preview').contentFrame().getByRole('link',{name:'Sepet',exact:true}).click();await p.waitForURL('**#laptop/1440/sepet');await p.goBack();assert(p.url().endsWith('/urun'),'back hash')});
await test('Viewer responsive dropdown at 600',async()=>{await p.setViewportSize({width:600,height:900});assert(await p.locator('#device-select').isVisible(),'dropdown');assert(!await p.locator('.devices').isVisible(),'sidebar hidden')});
await test('TV initial focus, arrows, dark mode and handoff',async()=>{await p.setViewportSize({width:1920,height:1080});await go('tv/4k/ana-sayfa.html?embed=1');const before=await p.evaluate(()=>document.activeElement?.textContent);await p.keyboard.press('ArrowRight');const after=await p.evaluate(()=>document.activeElement?.textContent);assert(before!==after,'D-pad move');assert(await p.locator('body').getAttribute('data-theme')==='dark','TV dark');await go('tv/4k/odeme.html?embed=1');assert((await p.locator('main').innerText()).includes('K74QX'),'device code')});
await test('Desktop category mega menu',async()=>{await p.setViewportSize({width:1440,height:900});await go('laptop/1440/ana-sayfa.html?embed=1');await p.getByRole('link',{name:'Tüm kategoriler',exact:true}).click();assert(await p.getByRole('dialog').isVisible(),'menu visible');assert(await p.getByRole('dialog').getByRole('link').count()===10,'10 categories')});
await test('TV handoff button opens matching phone page',async()=>{await go('tv/4k/odeme.html?embed=1');await p.getByRole('button',{name:'Telefon görünümünü aç',exact:true}).click();await p.waitForURL('**/mobil-dikey/390/odeme.html');assert(p.url().includes('/mobil-dikey/390/odeme.html'),'phone route')});
await test('Standalone device controls and large-screen fit',async()=>{await p.setViewportSize({width:1280,height:900});await go('masaustu/2560/ana-sayfa.html');await p.getByRole('button',{name:'Sığdır',exact:true}).click();const width=await p.locator('#device').evaluate(e=>e.getBoundingClientRect().width);assert(Math.abs(width-1280)<2,'fit width');await p.locator('#page-choice').selectOption('urun');await p.waitForURL('**/urun.html');assert(p.url().includes('masaustu/2560/urun'),'device route')});
fs.writeFileSync('/work/qa/interactions.json',JSON.stringify(out,null,2));await browser.close();console.log('passed',out.filter(r=>r.success).length,'/',out.length)
